apiVersion: v1
kind: PersistentVolume
metadata:
  name: byteman-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp
    subPath: byteman
